add_newline = true
# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[python]
format = "[$symbol $version]($style) "
symbol = "󰌠"
style = "bold yellow"

[nodejs]
format = "via [󰎙 $version](bold green) "

[battery]
full_symbol = "󰂅"
charging_symbol = "󰂄"
discharging_symbol = "󰂆"

